apiVersion: v1
kind: Service
metadata:
  name: {{ include "rspamd.fullname" . }}
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: {{ .Values.service.port }}
      targetPort: rspamd
      protocol: TCP
      name: rspamd
    - port: {{ .Values.service.controllerPort }}
      targetPort: controller
      protocol: TCP
      name: controller
  selector:
    {{- include "rspamd.selectorLabels" . | nindent 4 }}
